### ISSUE TITLE
gulp watch task improvements

### ISSUE THREAD

**Issue by mkoryak** [CaryLandholt/fatarrow#23]
We made changes to your watch task in the following ways that greatly speed it up:

1. Introduced a global `firstRun` flag that gets set to false in the watch task (which depends on all other tasks). 
When firstRun is false, we don't run the bower task. This is better then the flag to simply turn off bower since you get to run it once during a watch. We also don't clean the dist directory when it is false.

2. We split up the watch task to watch different components of the app and update them individually. Here is the not-so-elegant code to do this:

``` coffeescript
gulp.task 'watch', ['build'], ->
    isFirstRun = false # don't cleanup the dist directory

    extensions = []
    .concat EXTENSIONS.VIEWS.COMPILED
    .concat EXTENSIONS.VIEWS.UNCOMPILED

    sources = [].concat ("**/*#{extension}" for extension in extensions)

    gulp
    .watch sources, {cwd: SRC_DIRECTORY, maxListeners: 999}, ['views']
    .on 'error', onError

    extensions = []
    .concat EXTENSIONS.SCRIPTS.COMPILED
    .concat EXTENSIONS.SCRIPTS.UNCOMPILED

    sources = [].concat ("**/*#{extension}" for extension in extensions)

    gulp
    .watch sources, {cwd: SRC_DIRECTORY, maxListeners: 999}, ['scripts']
    .on 'error', onError

    extensions = []
    .concat EXTENSIONS.STYLES.COMPILED
    .concat EXTENSIONS.STYLES.UNCOMPILED

    sources = [].concat ("**/*#{extension}" for extension in extensions)

    gulp
      .watch sources, {cwd: SRC_DIRECTORY, maxListeners: 999}, ['styles']
      .on 'error', onError

    gulp
      .watch 'index.html', {cwd: SRC_DIRECTORY, maxListeners: 999}, ['spa']
      .on 'error', onError
```

Unrelated to the above suggestion (or maybe related, because of the modifications we made)

I have an issue where the watch task dies intermittently during a clean like this:

```bash
[15:29:57] Starting 'clean:working'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, lstat '/Users/misha/Work/main-app/app/bower_components/_/vendor/angular-strap/scripts/dimensions.js'
```
Ive tried wrapping things in try catch statements but maybe I did it wrong? Either way, a clean shouldnt be to upset if it cant find a file to delete :)

**Comment by nmehta6** [comment]
As a part of #32, I am introducing this flag. I can include not going to bower as well.

**Comment by nmehta6** [comment]
Also, I think that it's a great idea to not spend time processing file types that are not being used. What if we include this as part of the configuration in config.coffee?

**Comment by CaryLandholt** [comment]
yep

**Comment by nmehta6** [comment]
@mkoryak sorry about the delay but your suggestions about running bower only the first time and the ability to only compile languages you use is in. Please let me know if you have any issues.
