### ISSUE TITLE
Question about using a real backend

### ISSUE THREAD

**Issue by nmehta6** [CaryLandholt/fatarrow#29]
I am currently when using the `--backend` flag to exclude angular's `$httpBackend`. I have modified gulp tasks to drop off the build output to another location where my backend expects it. All this works great. However, I have been thinking about making the connect server that is spun up a proxy server. This way, you could have your api running wherever, and you can code your frontend against it. I wanted to see if you have any thoughts on this. Shouldn't be hard to wire it up, but do you think it belongs on fatarrow?

**Comment by nmehta6** [comment]
Hey any chance you will consider a pull request for this feature? Please feel free to let me know if you have any concerns around this.

**Comment by CaryLandholt** [comment]
Sorry. Still need to study this. I'll do it this weekend. :)

**Comment by nmehta6** [comment]
Will you be able to review/test a few pull requests I have?

**Comment by CaryLandholt** [comment]
yes, but it probably won’t be until the weekend

**Comment by nmehta6** [comment]
Ok great. Thanks.

**Comment by nmehta6** [comment]
No need to drop off files to IIS, Apache, etc. Just use the built in proxy to call a backend!
