### ISSUE TITLE
CSS injection

### ISSUE THREAD

**Issue by nmehta6** [CaryLandholt/fatarrow#34]
Reloading the browser after CSS change is so 2014 :)

This seems pretty straightforward with BrowserSync.

**Comment by nmehta6** [comment]
This can be a useful feature but it will require me to stop cleaning out the `dist` folder on file save. I have some reservations around this. Need to think about this one. @CaryLandholt Do you have any thoughts or opinions?

**Comment by CaryLandholt** [comment]
Need to at least provide an option to clean or not to clean.

**Comment by nmehta6** [comment]
That's a good idea. This will only work in Chrome, so thinking it should be off by default and a flag can turn on this feature.

**Comment by CaryLandholt** [comment]
Agee
