### ISSUE TITLE
Bower task suppresses output

### ISSUE THREAD

**Issue by mniebling** [CaryLandholt/fatarrow#87]
Lately I find that I am interested in the package versions that got installed / updated as a result of the `gulp bower` task. I usually end up doing `bower list` after the task completes to see this.

What do you think about exposing bower's log output as part of this task?

**Comment by nmehta6** [comment]
I like your suggestion. In fact, we can improve the package install process even further by listening to events listed at http://bower.io/docs/api/#programmatic-api

**Comment by nmehta6** [comment]
Now `bower install` will fire as part of `npm install`. This will produce all the console output as well as allow us to use bower's conflict resolution.
